### ISSUE TITLE
Support isBetween API?

### ISSUE THREAD

**Issue by HelKyle** [smallwins/spacetime#13]
How about supporting **isBetween** api for checking if a date is in the range

``` javascript
var now = spacetime().now()
var start = spacetime('July 2, 2017 5:01:00')
var end = spacetime('July 2, 2018 5:01:00')

// return true or false
now.isBetween(start, end)
```

**Comment by spencermountain** [comment]
hi HelKyle, yeah, i like that. happy to merge a pr. Right now you could just do 
`now.isAfter(start) && now.isBefore(end)`, though i admit that is more complicated than it oughta be.

**Comment by HelKyle** [comment]
how about this 
#14
