### ISSUE TITLE
Season incorrect

### ISSUE THREAD

**Issue by uitgewis** [smallwins/spacetime#16]
The season in the southern hemisphere is incorrectly being reported as being the same as the northern hemisphere.

Example:
It's currently winter in the southern hemisphere, but the library reports it as summer.

**Comment by spencermountain** [comment]
hi Ferdi, yup!  never did this properly. it should be pretty easy to do. #6 
i'm going on vacation this week, so unless you figure it out, i'll look at it when i get back next week

**Comment by spencermountain** [comment]
hey, so if you're one step north of the equator in august, it's summer, but you take a step south and it's winter?  never thought about how dumb this is.

**Comment by ryanblock** [comment]
Well, places that are equatorial don't really experience seasons like the folks smack dab in the middle of hemispheres do. So the answer is yes, technically, but not practically.

**Comment by uitgewis** [comment]
Indeed! Though, I think it may be better to rather remove this functionality than attempt to support it.

That is, unless you'd like to keep a list of all countries, but as @ryanblock said, seasons are meaningless for countries near the equator.

**Comment by spencermountain** [comment]
hey Ferdi, this works now in v1.3
check it out here https://runkit.com/spencermountain/59a089ff4f689d0012aef498
cheers

**Comment by sebszocinski** [comment]
I don't think this is working properly, we've just switched over to Summer here in Australia (Dec 1st) and the package is reporting Winter. Yesterday however it was reporting Spring, so i'm not sure how it goes from Spring to Winter?
