### ISSUE TITLE
[Feature] Allow manual i18n

### ISSUE THREAD

**Issue by pbarbiero** [smallwins/spacetime#18]
It would be nice to have basic support for translating the days and months.

While it would also be nice to include a bunch of locales ready to go, its not necessary if a method is exposed to update the strings.

Is this something you would consider, and would you humor a pull request to add this behavior if I get time to do so?

**Comment by ryanblock** [comment]
→ https://github.com/smallwins/spacetime/issues/19#issuecomment-320086140

**Comment by spencermountain** [comment]
hey Phillip, for sure. Would be happy to merge this, if you figured out a way that made sense to do it. As long as filesize stays small, and english use is on the fast-path, it's all yours!

**Comment by pbarbiero** [comment]
Resolved in #24
