### ISSUE TITLE
Bug with southern hemisphere and DST

### ISSUE THREAD

**Issue by StefanoMagrassi** [smallwins/spacetime#27]
It seems that the DST "change" property it's not rightly handled in the southern hemisphere.

For example, if you set as date `2017-10-09 12:00 UTC` and go to *America/Sao_Paulo* timezone, `hour()` method should return `09:00` because ([ref](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)):

- UTC standard offset is **-3**;
- UTC **DST** offset is **-2**;
- DST starts on october 15th

Coherently, if you change date to `2017-10-16` it should return as `10:00`.

At [this line](https://github.com/smallwins/spacetime/blob/master/src/timezone/index.js#L40) the `dst.change` is constantly set to `-60`, but in the case above it should be `+60`.

Indeed, the `timezone().offsets` property returns `{base: -240, dst: -180}` instead of `{base: -180, dst: -120}`

Same happens with *America/Campo_Grande* and *America/Cuiaba*.

I can't understand if this pattern (inverse of current `dst.change`) could be applied to every timezone in the southern hemisphere.

Take a look to [this repl](https://repl.it/MUPT/0)

**Comment by spencermountain** [comment]
oh hey! duh! you're absolutely right.
man, thank you Stefano.
I should've caught this.
Will fix it pronto.
thanks!

**Comment by StefanoMagrassi** [comment]
You're welcome.

Please remember that I'm not 100% sure the pattern could be applied to every southern hemisphere timezone. Should be done further investigations

**Comment by spencermountain** [comment]
hey, have been busy. haven't forgot about this.
Hope to get it at the end of the week.

**Comment by spencermountain** [comment]
hey! i got this in `v2.1.1`. 

you can see it [here](https://runkit.com/spencermountain/5a0f5405cfd0970012f63bac) matching up with what it oughta be:
![image](https://user-images.githubusercontent.com/399657/32969796-63c9d930-cbb4-11e7-94e8-06a80baefe74.png)


[relevant tests](https://github.com/smallwins/spacetime/blob/dev/test/hemisphere.test.js)
thanks!
