### ISSUE TITLE
Implement `fromNow` method

### ISSUE THREAD

**Issue by shaungrady** [smallwins/spacetime#46]
Greetings, I was curious if implementing Moment's `fromNow` feature is in the roadmap? It seems like it wouldn't be too tough to do by leveraging `diff`.

Just thinking through the rough logic:
- Diff on `years`; if `years` >= 1, `${years} year(s) ago`, else...
- Diff on `months`; if `months` >= 1, `${months} month(s) ago` else...
- Et cetera.

Pluralization of the time unit would be handled, of course, and the [logic Moment uses](http://momentjs.com/docs/#/displaying/fromnow/) would be easy to duplicate.

If this is something you'd like to support, and the rough approach above sounds like the right path to you, I could do a bit of work and open a PR.

**Comment by spencermountain** [comment]
hey shaun! yeah, great idea. Your approach is a good one.
Would it return text like moment, or some kinda structured data? Both could be useful.
PR! PR!

**Comment by shaungrady** [comment]
Interesting, I had never considered anything other than a string output. What do you imagine an object might entail? Just thinking out loud, here, but maybe something like...


``` javascript
{
  number: 58,
  unit: 'minute',
  time: 'an hour',
  calendar: 'Today'
}
```

``` javascript
{
  number: 6,
  unit: 'day',
  time: '6 days',
  calendar: 'Last Monday'
}
```

Any other ideas?

**Comment by spencermountain** [comment]
agh yeah, good point. I think it'd be fair to blast-out a few forms, whatever you feel makes sense, like this:
```js
spacetime('april 1 2019').fromNow()
{
  diff: { //raw differences in units
    years:1,
    months:0,
    days:28,
    hours:3 ....
  },
  rough:"1 year",
  medium: "1 year and 28 days",
  precise:"1 year, 28 days, and 3 hours"
}
```
i dunno, different precisions for different people maybe. Your cut-offs may have all-sorts of subjective stuff - like maybe showing ' and 11 seconds' isn't cool, but 'and 30 seconds' is cool. ¯\_(ツ)_/¯
go for it!

**Comment by shaungrady** [comment]
I like that diff idea and having a more precise variation. How about this?

``` javascript
{
  diff: {
    years: 1,
    months: 11,
    days: 15,
    hours: 3,
    minutes: 12,
    seconds: 9
  },
  rounded: '2 years',
  qualified: 'almost 2 years', // or 'over 2 years' or '2 years'
  precise: '1 year, 11 months'
}
```

``` javascript
{
  diff: {
    years: 0,
    months: 12,
    days: 29,
    hours: 3,
    minutes: 12,
    seconds: 9
  },
  rounded: 'a year',
  qualified: 'almost a year',
  precise: '12 months, 29 days'
}
```
  
#### Qualifiers
Break up unit into 6ths, first 2/6ths has no qualifier, second 3/6ths has `'over'` qualifier, last 1/6th has `'almost'` qualifier:

- Years
  - Year and 1–4 months: `''`
  - Year and 5–10 months: `'over'`
  - Year and 11, 12 months: `'almost'` (following year)

- Months
  - Month and 1–10 days: `''`
  - Year and 11–25 days: `'over'`
  - Year and 26–30 days: `'almost'` (following month)

Et cetera.

**Comment by spencermountain** [comment]
🤗 love it!

**Comment by shaungrady** [comment]
I've opened a PR (#48). Wasn't able to leverage `diff`, since it's based on calendar months—so I copied the diffing logic from Moment. There are also a few tests in Travis that are failing that are unrelated to the new tests; must be failing due to the DST change that occurred this morning.

**Comment by shaungrady** [comment]
There also appears to be an issue with Travis where, if a test throws an error, it doesn't break the build.

**Comment by spencermountain** [comment]
very cool!
yeah, that's my bad. There's actually an insane off-by-one issue that can trigger at certain hours, which I haven't figured-out yet.
bonus points for writing this during a dst-change
cheers
