### ISSUE TITLE
Leap year support in dayOfYear()

### ISSUE THREAD

**Issue by ryanblock** [smallwins/spacetime#8]
👇 
```js
for(let i = 0; i < 15; i++) {
  var s = spacetime({
    year: 2014 + i
  }).endOf('year');
  console.log(s.dayOfYear());
}
```

**Comment by spencermountain** [comment]
hey @ryanblock , that's clever - is this right?
```
2014 366
2015 366
2016 367
2017 366
2018 366
2019 366
2020 367
2021 366
2022 366
2023 366
2024 367
2025 366
2026 366
2027 366
2028 367
```
... because the jan 1st is `1st`... the last day is 366th...?

**Comment by ryanblock** [comment]
Last time I checked, regular years have 365, not 366 days (and leap years +1 day).

**Comment by spencermountain** [comment]
got it in `v2.1.1` [check it out~](https://github.com/smallwins/spacetime/blob/dev/test/leapYear.test.js#L106)
thanks!
