### ISSUE TITLE
Basic `window.Intl` fallback to guess timezone

### ISSUE THREAD

**Issue by ryanblock** [smallwins/spacetime#9]
(If the env doesn't support that spec yet)

**Comment by krlk89** [comment]
I am not sure if that is what OP meant with this issue, but it would be nice if the fallback timezone wouldn't be hardcoded to 'Canada/Pacific'.

I think it would be better if, for example, getTimezoneOffset method or timezone info from a Date object is used when assigning a fallback timezone.

Sadly, IE11 returns undefined for Intl.DateTimeFormat().resolvedOptions().timeZone so a (hopefully) more accurate fallback would be nice for that legacy browser.

**Comment by spencermountain** [comment]
yep. i totally agree.
i'll try it this week. i suppose the eventual fallback oughta be utc, too... That or the bermuda triangle.
we could add a config in the options param.
cheers

**Comment by spencermountain** [comment]
changed the fallback to UTC, if no Intl is present
will release in v3.0.0
cheers!
